// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    ',
    appId: '1:1029711433782:ios:de9e0bdcd30a40f164c897',
    messagingSenderId: '1029711433782',
    projectId: 'dyfdlin',
    storageBucket: 'dyfdlin.appspot.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:1029711433782:web:5c492ff5208466dd64c897',
    messagingSenderId: '1029711433782',
    projectId: 'dyfdlin',
    authDomain: 'dyfdlin.firebaseapp.com',
    storageBucket: 'dyfdlin.appspot.com',
    measurementId: 'G-ECFZJ5RHPS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNwKQQtd8OdkRF2TyCeCDwCqY5b9QciY',
    appId: '1:1029711433782:ios:de9e0bdcd30a40f164c897',
    messagingSenderId: '1029711433782',
    projectId: 'dyfdlin',
    storageBucket: 'dyfdlin.appspot.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylVuwEem1LFESC3lRp79dYW_X_uOJdWQ',
    appId: '1:1029711433782:android:7a8e72a6c42942b264c897',
    messagingSenderId: '1029711433782',
    projectId: 'dyfdlin',
    storageBucket: 'dyfdlin.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOWToChk7DAj61HOecEkxh-il4r2EfRls',
    appId: '1:1029711433782:web:206bf43599c64c5c64c897',
    messagingSenderId: '1029711433782',
    projectId: 'dyfdlin',
    authDomain: 'dyfdlin.firebaseapp.com',
    storageBucket: 'dyfdlin.appspot.com',
    measurementId: 'G-KDYCP1CLZE',
  );

}
